### ISSUE TITLE
Compare cached JSON with JSON on server

### ISSUE THREAD

**Issue by thomascsorbamedia** [eyeballz/HanekeSwiftiOS7Test#1]
I want to know if it is possible to compare the json i cache to the json on the server?
I have a json query that may change, if i change it the query is different, when i go to the app (killed it first) i expect to see the different results. The problem is that i can only see the cached data.

Possible other way:
Maybe reverse the order of checking, always check with source and if source is different then refetch all data?

quote from readme
"memory, disk or NSURLCache. If not available, Haneke will fetch the JSON from the source"

If there someone can help me asap i would be very thankful, because i'm working on a project with a deadline :)

i made this project using your method on using hanekeSwift in IOS 7
this is my code maybe i am doing something wrong

```
let cache = HNKCache<JSON>(name: "dasboard")
let URL = NSURL(string: "http://example.com/loadResults.php?action=posts")!
var cacheResult: NSArray = []
cache.fetch(URL: URL).onSuccess { JSON in
cacheResult = JSON.dictionary["posts"] as NSArray
    println(cacheResult)
    self.tableData = cacheResult
    self.tableView!.reloadData()
}.onFailure{error in
    println("error: \(error)")
}
```

Greets, Thomas

**Comment by eyeballz** [comment]
Hey, this is just an iOS7 Test for Haneke Swift. Please refer to the main repo.

**Comment by thomascsorbamedia** [comment]
i did, please look there if you can
